baseURL = 'https://panzerschokolade.klingt.org'
languageCode = 'en-us'
defaultContentLanguage = "en"
title = 'Panzerschokolade'
description = "Ewige Blumenkraft"
keywords = ["disktree"]

buildFuture = true
disableHugoGeneratorInject = true
disablePathToLower = true
enableRobotsTXT = true
newcontenteditor = "nvim"

[imaging]
    quality = 90

[outputs]
    home = ["HTML"]
    section = ["HTML"]
    page = ["HTML"]

[params.social]
    twitter = "eichhorny"
    mixcloud = "panzerschokolade"

